

# -----
url: https://gallerytest.pauliver.com
baseurl: /


# -----
# Colors are set in data/template.yml
# explore moving them here at some point in the future

# -----
# Site settings
title: Awesome Title
email: your-email@domain.com
description: "located in _config.yml. It will appear in your document head meta (for Google search results) and in your feed.xml site description."

# -----
# The header at the top of the page
header_background: /img/header-bg.jpg
header_heading: Welcome To Our Studio!
header_leadin: It's Nice To Meet You
header_button_text: Tell Me More
header_button_target: portfolio
header_button_enabled: true

# from the removed contact section
contact_background: /img/map-image.png


# -----
# Subjects Page
subjects_heading: Our Favorite Subjects
subjects_subheading: The people and places that we love to photograph.
subjects_footer: "Always be respectful. For people: Don't say anything you wouldn't want your mother to see. For places: please take nothing but pictures and leave nothing but footprints."

# Subjects List
subjects:
- name: Kay Garland
  pic: 1
  description: Lead Designer
  social:
    - title: twitter
      url: #
    - title: facebook
      url: #
    - title: stack-overflow
      url: #

- name: Larry Parker
  pic: 2
  description: Lead Marketer
  social:
    - title: twitter
      url: #
    - title: facebook
      url: #
    - title: linkedin
      url: #

- name: Diana Petersen
  pic: 3
  description: Lead Developer
  social:
    - title: twitter
      url: #
    - title: facebook
      url: #
    - title: google-plus
      url: #
      
- name: Kay Garland
  pic: 1
  description: Lead Designer
  social:
    - title: twitter
      url: #
    - title: facebook
      url: #
    - title: stack-overflow
      url: #

- name: Larry Parker
  pic: 2
  description: Lead Marketer
  social:
    - title: twitter
      url: #
    - title: facebook
      url: #
    - title: linkedin
      url: #

- name: Diana Petersen
  pic: 3
  description: Lead Developer
  social:
    - title: twitter
      url: #
    - title: facebook
      url: #
    - title: google-plus
      url: #


# -----
gear_heading: Gear
subjects_subheading: The equiptment we like to use.
gear:
- name: Lens
  pic: 3
  class: fa-shopping-cart
  description: "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Minima maxime quam architecto quo inventore harum ex magni, dicta impedit."

- name: Camera
  pic: 3
  class: fa-laptop 
  description: "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Minima maxime quam architecto quo inventore harum ex magni, dicta impedit."

- name: Lens
  pic: 3
  class: fa-lock
  description: "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Minima maxime quam architecto quo inventore harum ex magni, dicta impedit."

- name: Camera
  pic: 3
  class: fa-shopping-cart
  description: "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Minima maxime quam architecto quo inventore harum ex magni, dicta impedit."

- name: Lens
  pic: 3
  class: fa-laptop 
  description: "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Minima maxime quam architecto quo inventore harum ex magni, dicta impedit."

- name: Camera
  pic: 3
  class:  fa-lock
  description: "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Minima maxime quam architecto quo inventore harum ex magni, dicta impedit."

# -----
# Site Social networks usernames (many more available: instagram,  flickr, facebook,  pinterest, dribbble, google-plus, tumblr,  linkedin, etc.)
social:
  - title: twitter
    url: http://twitter.com/jekyllrb
  - title: modelmayhem
    url: https://www.modelmayhem.com/
  - title: github
    url: http://github.com/jekyll

# Postal address (add as many lines as necessary)
address:
  - line: 3481 Melrose Place
  - line: Beverly Hills, CA 90210

# Build settings
markdown: kramdown
permalink: pretty

# -----
# Portfolio Settings
portfolio_heading: Portfolio
portfolio_subheading: Lorem ipsum dolor sit amet consectetur.
portfolio_footer: "Always be respectful. For people: Don't say anything you wouldn't want your mother to see. For places: please take nothing but pictures and leave nothing but footprints."
